### ISSUE TITLE
Checking GRammar make the compose window too tall

### ISSUE THREAD

**Issue by Cygn** [nuald/thb-gramchecker#18]
Clicking "Grammar" on compose window makes the window terribly tall, with a minimum height well above my screen's. (And I'm surprised nobody complained so far 'cause it makes it quite unusable. So probably something's odd on my side)
TB 60.8.0 (64 bits) on Fedora 30

**Comment by nuald** [comment]
I've tried the fresh default Fedora 30 installation and do not see the issue. Could you please clarify what window manager do you use (it's just a guess though)? It also could be a conflict with other extensions.

**Comment by Cygn** [comment]
OK, I've investigated a bit, it isn't related to other extensions, and does the same under Gnome and Plasma - both up to date. 

I use several identities, some with built-in signatures. This happens with only those accounts - regardless if the signature's html or plain text. The increase in window height looks somehow related to the signature size.

Let me know where I can  look further.

**Comment by nuald** [comment]
I've verified the use-cases you mentioned, but still couldn't reproduce it. However, as new Thunderbird was not compatible with the version you've tested, I had to release the new version and it may have no issues you've seen. Please re-verify.

**Comment by Cygn** [comment]
Unfortunately it still does it with the latest TB. It depends on if the message body has HTML / richtext (in this case the window gets resized) or text (which works OK). I've recorded 2 videos to show the issue, here. [here](https://cloud.isir.upmc.fr/owncloud/index.php/s/aqDpBGadwxbNenr). The text comes from Libreoffice. If I copy/paste as it is, grammar-tool resizes the window. If I paste as pure text it does not.
Let me know where I can look for better logs.

**Comment by flhofer** [comment]
> Unfortunately it still does it with the latest TB. It depends on if the message body has HTML / richtext (in this case the window gets resized) or text (which works OK). I've recorded 2 videos to show the issue, here. [here](https://cloud.isir.upmc.fr/owncloud/index.php/s/aqDpBGadwxbNenr). The text comes from Libreoffice. If I copy/paste as it is, grammar-tool resizes the window. If I paste as pure text it does not.
> Let me know where I can look for better logs.

Same here. Thunderbird 68.4.1 on Ubuntu 18.04 LTS, it expands the window when you click grammar  and the message contains HTML (images ecc). Tried a few cases

**Comment by neillbell** [comment]
Just to chime in here, I'm seeing the same thing with Thunderbird 68.4.1, Ubuntu 18.04.4 and the XFCE desktop.

**Comment by TheAifam5** [comment]
Same thing here. even 4K screen is too small :D I can't even make the window smaller.

Workaround:
Rotate your monitor 90* :D

**Comment by ProfRon** [comment]
I think this may have to do with the length of the email in the compose window!

I took a very long email (actually, a chain of emails), and highlighted sections of various lengths. Since only the selected parts show up in the compose window (as quotes), it was fairly easy to start with otherwise identical compose windows, just with varying length. 

Up to a certain length, the window grows, but not by too much. Once the text gets too long, the window size grows out of control (and I can't resize the window anymore!).

This may have to do with the amount of text being checked or it may have to do with the length of the "diagnostic" output from LanguageTool. In my tests, both grew (I suspect they're roughly proportional to each other). I suppose we could create some fake emails with a lot of text but little output from LanguageTool. It would be harder to create text with a lot of diagnostic output from little original text... 

I cannot reproduce a connection with signatures (as suggested by others, above). I have signatures on all of my accounts, and on one I have fairly complicated HTML, on another fairly simple text, but sometimes I get these giant compose windows and sometimes I don't.  

This is a very old problem. It's been there for a _long_ time for me. 

I'm currently using Arch Linux (so, now version number there), Gnome 3.36 , Thunderbird 68.7.0, gramhecker 0.9 ("updated on 16 Dec 2019") and LanguageTool version "4.9 (2020-03-24 14:19, d6a675b)".  I'm using a local LanguageTool server (running on my notebook).  I also have the LanguageTool extensions for LibreOffice and for Firefox, and they work OK.  I'm only having problems with Thunderbird.

**Comment by ProfRon** [comment]
Update: I'm pretty sure it has to do with the amount of output created by LanguageTool, and not (directly) the amount of text checked. I don't have real tests (yet), but it subjectively seems to go that way. 

An aside: Having the output from LanguageTool in one block, down at the bottom of the Compose window,  is suboptimal anyways. It makes it hard to find where the error is.  It might make more sense to try to get an in-line feedback like the one supplied by the Firefox LanguageTool extension. That would make fixing this bug unnecessary - and this issue "redundant" (with issues #1  and/or #5 ).

**Comment by ProfRon** [comment]
**Work-around, at least for Linux/Gnome:** I can move the window with Alt+Mouse-Click-and-Drag (hold down the alt key, then use the mouse to move the window). With this trick, you can move the window up until you can read the output from LangaugeTool. 

You cannot change the height of the window (you can change the width). 

By moving the window up and down you can read the output of LanguageTool, and then go back to edit your email. This is _very_ inconvenient, but if the window is not _too_ large, it _can_ be usable.
